### ISSUE TITLE
%namecolors.name% placeholder isn't getting registered

### ISSUE THREAD

**Issue by malpkakefirek** [GavvyDizzle/NameColors#1]
There are no errors in console. The plugin itself hooks into papi successfully, but no placeholders are registered.

Versions:
NameColors 1.0.0
ServerUtils 1.0.6
PlaceholderAPI 2.11.5
Paper version git-Paper-426 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ccefdc)

**Comment by GavvyDizzle** [comment]
The `%namecolors.name%` placeholder was incorrect on the plugin's Spigot page. It should be `%namecolors_name%`. I have updated it on there too.
